--DDL Database Definition Language

--criar banco de dados
CREATE DATABASE [Roomly]
USE [Roomly]

--criar tabelas
CREATE TABLE TiposUsuario
(
	IdTipoUsuario UNIQUEIDENTIFIER PRIMARY KEY,
	TituloTipoUsuario VARCHAR(20) NOT NULL
)

CREATE TABLE Equipamentos
(
	IdEquipamento UNIQUEIDENTIFIER PRIMARY KEY,
	TituloEquipamento VARCHAR(100) NOT NULL
)

CREATE TABLE Usuario
(
	IdUsuario UNIQUEIDENTIFIER PRIMARY KEY,
	IdTipoUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TiposUsuario(IdTipoUsuario) NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(256) NOT NULL UNIQUE,
	Senha VARCHAR(100) NOT NULL
)

CREATE TABLE Sala
(
	IdSala UNIQUEIDENTIFIER PRIMARY KEY,
	IdEquipamento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Equipamentos(IdEquipamento) NOT NULL,
	TituloSala VARCHAR(50) NOT NULL,
	Capacidade INT NOT NULL
)

CREATE TABLE Reserva
(
	IdReserva UNIQUEIDENTIFIER PRIMARY KEY,
	IdUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL,
	IdSala UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Sala(IdSala) NOT NULL,
	DataReserva DATE NOT NULL,
	HorarioReserva TIME NOT NULL
)
